package com.jiudi.shopping.bean;

public class CartTitleBean {
    public String id;
    public String mer_id;
    public String image;
    public String store_name;
    public String store_info;
    public String keyword;
    public String cate_id;
    public String price;
    public String vip_price;
    public String ot_price;
    public String postage;
    public String basics_commission;
    public String parent_commission;
    public String unit_name;
    public String sort;
    public String sales;
    public String stock;
    public String is_show;
    public String is_hot;
    public String is_benefit;
    public String is_best;
    public String is_new;
    public String description;
    public String add_time;
    public String is_postage;
    public String is_del;
    public String is_special;
    public String mer_use;
    public String give_integral;
    public String cost;
    public String is_seckill;
    public String is_bargain;
    public String ficti;
    public String browse;
    public String code_path;
    public String coupon;
    public String userLike;
    public String like_num;
    public String userCollect;
}
