package com.jiudi.shopping.bean;

public class DeviceDetail {
    public String user_name;
    public String sys_time;
    public String datetime;
    public String heart_time;
    public String sudu;
    public String status;
    public String create_time;
    public String remark;
    public String use_time;
    public String factory_date;
    public String tel;
    public String sex;
    public String sim_id;
    public String phone;
    public String user_id;
    public String grade;
    public String sale_type;
    public String service_flag;
    public String product_type;
    public String iconType;
    public String out_time;
    public String jingdu;
    public String weidu;
    public String su;
    public String owner;
    public String jingwei;
    public String alarm;
    public String deviceRemark;
    public String alarmFuel;
    public String fuelPerHKM;
    public String fuelSize;
    public String maxFuelV;
    public String minFuelV;
    public String macVersion;
    public String FuelTotalHeight;
    public String carColor;
    public String VideoConfig;
    public String HighTempAlarm;
    public String LowTempAlarm;
    public String ActivationCode;
    public String VendorCode;
    public String OwnerId;
    public String PColour;
    public String TerminalType;
    public String DeviceCode;
    public String SpeedDuration;
//    bean.user_name=jsonObject.optString("user_name");
//    bean.sys_time=jsonObject.optString("sys_time");
//    bean.datetime=jsonObject.optString("datetime");
//    bean.heart_time=jsonObject.optString("heart_time");
//    bean.sudu=jsonObject.optString("sudu");
//    bean.status=jsonObject.optString("status");
//    bean.create_time=jsonObject.optString("create_time");
//    bean.remark=jsonObject.optString("remark");
//    bean.use_time=jsonObject.optString("use_time");
//    bean.factory_date=jsonObject.optString("factory_date");
//    bean.tel=jsonObject.optString("tel");
//    bean.sex=jsonObject.optString("sex");
//    bean.sim_id=jsonObject.optString("sim_id");
//    bean.phone=jsonObject.optString("phone");
//    bean.user_id=jsonObject.optString("user_id");
//    bean.grade=jsonObject.optString("grade");
//    bean.sale_type=jsonObject.optString("sale_type");
//    bean.service_flag=jsonObject.optString("service_flag");
//    bean.product_type=jsonObject.optString("product_type");
//    bean.iconType=jsonObject.optString("iconType");
//    bean.out_time=jsonObject.optString("out_time");
//    bean.jingdu=jsonObject.optString("jingdu");
//    bean.weidu=jsonObject.optString("weidu");
//    bean.su=jsonObject.optString("su");
//    bean.owner=jsonObject.optString("owner");
//    bean.jingwei=jsonObject.optString("jingwei");
//    bean.alarm=jsonObject.optString("alarm");
//    bean.deviceRemark=jsonObject.optString("deviceRemark");
//    bean.alarmFuel=jsonObject.optString("alarmFuel");
//    bean.fuelPerHKM=jsonObject.optString("fuelPerHKM");
//    bean.fuelSize=jsonObject.optString("fuelSize");
//    bean.maxFuelV=jsonObject.optString("maxFuelV");
//    bean.minFuelV=jsonObject.optString("minFuelV");
//    bean.macVersion=jsonObject.optString("macVersion");
//    bean.FuelTotalHeight=jsonObject.optString("FuelTotalHeight");
//    bean.carColor=jsonObject.optString("carColor");
//    bean.VideoConfig=jsonObject.optString("VideoConfig");
//    bean.HighTempAlarm=jsonObject.optString("HighTempAlarm");
//    bean.LowTempAlarm=jsonObject.optString("LowTempAlarm");
//    bean.ActivationCode=jsonObject.optString("ActivationCode");
//    bean.VendorCode=jsonObject.optString("VendorCode");
//    bean.OwnerId=jsonObject.optString("OwnerId");
//    bean.PColour=jsonObject.optString("PColour");
//    bean.TerminalType=jsonObject.optString("TerminalType");
//    bean.DeviceCode=jsonObject.optString("DeviceCode");
//    bean.SpeedDuration=jsonObject.optString("SpeedDuration");
}
