package com.nado.shopping.bean;

public class XingCheng {
    public String totalfuelUsed;
    public String distance;
    public String fuelHKM;
    public String totalSpeedoverSeconds;
    public String maxspeed;
    public String brakeTimes;
    public String emergencyBrakeTimes;
    public String speedupTimes;
    public String emergencySpeedupTimes;
    public String speed;
    public String maxTempc;
    public String maxEngRPM;
    public String btime;
    public String etime;
    public String strokeTime;
    public String jsType;
    public String driveTime;
    public String fraction;
    public String random;
    public String coulometric;
    public String powerv;
    public String overtimeDriverMinutes;
    public String BeginTime;
    public String EndTime;
    public String IdlingTime;
//    bean.totalfuelUsed=jsonObject.optString("totalfuelUsed");
//    bean.distance=jsonObject.optString("distance");
//    bean.fuelHKM=jsonObject.optString("fuelHKM");
//    bean.totalSpeedoverSeconds=jsonObject.optString("totalSpeedoverSeconds");
//    bean.maxspeed=jsonObject.optString("maxspeed");
//    bean.brakeTimes=jsonObject.optString("brakeTimes");
//    bean.emergencyBrakeTimes=jsonObject.optString("emergencyBrakeTimes");
//    bean.speedupTimes=jsonObject.optString("speedupTimes");
//    bean.emergencySpeedupTimes=jsonObject.optString("emergencySpeedupTimes");
//    bean.speed=jsonObject.optString("speed");
//    bean.maxTempc=jsonObject.optString("maxTempc");
//    bean.maxEngRPM=jsonObject.optString("maxEngRPM");
//    bean.btime=jsonObject.optString("btime");
//    bean.etime=jsonObject.optString("etime");
//    bean.strokeTime=jsonObject.optString("strokeTime");
//    bean.jsType=jsonObject.optString("jsType");
//    bean.driveTime=jsonObject.optString("driveTime");
//    bean.fraction=jsonObject.optString("fraction");
//    bean.random=jsonObject.optString("random");
//    bean.coulometric=jsonObject.optString("coulometric");
//    bean.powerv=jsonObject.optString("powerv");
//    bean.overtimeDriverMinutes=jsonObject.optString("overtimeDriverMinutes");
//    bean.BeginTime=jsonObject.optString("BeginTime");
//    bean.EndTime=jsonObject.optString("EndTime");
//    bean.IdlingTime=jsonObject.optString("IdlingTime");
}
